import {
  MARITIME_COUNTRIES_ISO2 as MARITIME_COUNTRIES_ISO2_LIST,
  MARITIME_COUNTRIES_ISO2_SET as MARITIME_COUNTRIES_ISO2_SET_INTERNAL,
} from '../data/maritimeCountries'

export const MARITIME_COUNTRIES_ISO2 = MARITIME_COUNTRIES_ISO2_LIST

export const MARITIME_COUNTRIES_ISO2_SET = MARITIME_COUNTRIES_ISO2_SET_INTERNAL

export const isMaritimeCountryIso2 = (iso2) => {
  if (!iso2) return false
  return MARITIME_COUNTRIES_ISO2_SET.has(String(iso2).toUpperCase())
}
